Repository SocialGouv/1000jours, pull requests merged in 2022-10, with the labels that each got.

#1452 fix(accessibility): label puce
  front/src/components/article/links.component.tsx
  front/src/components/html/li.component.tsx
  front/src/utils/aroundMe/aroundMe.util.ts
Labels: accessibilité, APPLI

#1436 feat(notif): paramétrer les notifs d'événement
  front/src/components/notification/notificationToggle.component.tsx
  front/src/constants/Labels.ts
  front/src/constants/storageKeys.constants.ts
  front/src/hooks/index.ts
  front/src/hooks/useEvents.ts
  front/src/screens/calendar/tabCalendarScreen.component.tsx
  front/src/screens/notificationsCenter/notificationsCenter.component.tsx
  front/src/utils/events/event.util.ts
  front/src/utils/events/events.util.test.ts
  front/src/utils/index.ts
  front/src/utils/notifications/notification.util.ts
  front/src/utils/notifications/notificationToggle.util.test.ts
  front/src/utils/notifications/notificationToggle.util.ts
Labels: APPLI, Epic::centre notifs

#1459 feat(notif): fréquence pour le moodboard
  front/src/components/index.ts
  front/src/components/notification/notificationPermissionInSettingsModal.component.tsx
  front/src/components/notification/notificationToggle.component.tsx
  front/src/components/notification/notificationsFrequency.component.tsx
  front/src/constants/Labels.ts
  front/src/constants/storageKeys.constants.ts
  front/src/utils/notifications/notification.util.ts
Labels: APPLI, Epic::centre notifs

#1468 Feat/notifications evenements essentiels 1413
  front/src/components/index.ts
  front/src/components/menu/menu.component.tsx
  front/src/components/notification/notificationToggle.component.tsx
  front/src/components/notification/notificationsEssentialEvents.component.tsx
  front/src/components/notification/notificationsFrequency.component.tsx
  front/src/constants/Labels.ts
  front/src/constants/storageKeys.constants.ts
  front/src/utils/events/event.util.ts
  front/src/utils/events/events.util.test.ts
Labels: APPLI, Epic::centre notifs

#1473 refacto(checkbox): mutualisation checkbox
  front/src/components/article/articlesFilter.component.tsx
  front/src/components/baseComponents/blueCheckbox.component.tsx
  front/src/components/baseComponents/greenRadioButton.component.tsx
  front/src/components/baseComponents/index.ts
  front/src/components/epdsSurvey/epdsGenderEntry.component.tsx
  front/src/components/epdsSurvey/epdsQuestion.component.tsx
  front/src/components/notification/notificationsEssentialEvents.component.tsx
Labels: APPLI

#1485 fix(notif): centre de notif
  front/src/constants/Labels.ts
Labels: bug, APPLI, Epic::centre notifs

#1486 fix(notif): radiobutton pour ios
  front/src/components/notification/notificationsFrequency.component.tsx
Labels: bug, APPLI, Epic::centre notifs

#1451 fix(accessibility): modal des filtres
  front/src/components/aroundMe/aroundMeFilter.component.tsx
Labels: accessibilité, APPLI

#1492 fix: 🐛 Corrige l'url des miniatures des videos
  back/strapi/api/video/models/video.js
  back/strapi/api/video/services/index.js
Labels: APPLI, Epic::videothèque
