Repository SocialGouv/1000jours, pull requests merged in 2022-11, with the labels that each got.

#1488 feat(videotheque): ajout tab videos dans la parentheque
  front/src/components/document/documentCard.component.tsx
  front/src/components/index.ts
  front/src/components/menu/menu.component.tsx
  front/src/components/parentheque/tabParenthequeDocuments.component.tsx
  front/src/components/parentheque/tabParenthequeVideos.component.tsx
  front/src/constants/Labels.ts
  front/src/screens/home/parentheque.component.tsx
Labels: APPLI, Epic::videothèque

#1493 Feat/videotheque data 1479
  front/src/assets/icomoon/icomoon.ttf
  front/src/assets/icomoon/selection.json
  front/src/components/baseComponents/icomoon.component.tsx
  front/src/components/baseComponents/iconWithBackground.component.tsx
  front/src/components/baseComponents/index.ts
  front/src/components/calendar/eventCard.component.tsx
  front/src/components/document/documentCard.component.tsx
  front/src/components/index.ts
  front/src/components/parentheque/tabParenthequeVideos.component.tsx
  front/src/components/parentheque/tabs/tabParenthequeDocuments.component.tsx
  front/src/components/parentheque/tabs/tabParenthequeVideos.component.tsx
  front/src/components/parentheque/video/videoCard.component.tsx
  front/src/constants/databaseQueries/homeDbQueries.constants.ts
  front/src/screens/home/parentheque.component.tsx
  front/src/types.tsx
Labels: APPLI, Epic::videothèque

#1501 feat(demographie): ajout département libellé
  back/strapi/api/informations-demographiques/models/informations-demographiques.settings.json
Labels: BO, EPDS

#1502 refacto(step): ajout et refacto TUs StepUtils
  front/src/screens/home/tabHomeScreen.component.tsx
  front/src/screens/onboardingAndProfile/profile.component.tsx
  front/src/utils/notifications/notification.util.ts
  front/src/utils/step/step.util.test.ts
  front/src/utils/step/step.util.ts
Labels: APPLI

#1506 fix(accessibility): maplist
  front/src/components/aroundMe/searchUserLocationOrPostalCodeCoords.component.tsx
  front/src/components/search/aroundMePoiList.component.tsx
  front/src/screens/search/aroundMeMapAndList.component.tsx
  front/src/utils/aroundMe/aroundMe.util.test.ts
  front/src/utils/aroundMe/aroundMe.util.ts
  front/src/utils/index.ts
  front/src/utils/number/number.util.test.ts
  front/src/utils/number/number.util.ts
  front/src/utils/search/search.util.test.ts
  front/src/utils/search/search.util.ts
Labels: accessibilité, APPLI

#1516 feat(notifications): ajout notification favoris
  front/src/components/notification/notificationModal.component.tsx
  front/src/constants/Labels.ts
  front/src/constants/notification.constants.ts
  front/src/jest/setup.js
  front/src/utils/favorites/favorites.util.test.ts
  front/src/utils/favorites/favorites.util.ts
  front/src/utils/index.ts
  front/src/utils/notifications/favorites/favoritesNotification.util.test.ts
  front/src/utils/notifications/favorites/favoritesNotification.util.ts
  front/src/utils/notifications/notification.util.ts
Labels: APPLI, Epic::favoris

#1524 feat(contact): ajout de la collection demande de contact
  back/strapi/api/demande-de-contact/config/routes.json
  back/strapi/api/demande-de-contact/models/demande-de-contact.js
  back/strapi/api/demande-de-contact/models/demande-de-contact.settings.json
  back/strapi/api/widget-epds-sources/models/widget-epds-sources.settings.json
Labels: BO, EPDS, WIDGET
