Repository SocialGouv/1000jours, pull requests merged in 2023-02, with the labels that each got.

#1600 refactor: 💡 Transforme certains écrans en 'Modal' (Profil, ...)
  front/src/components/html/li.component.tsx
  front/src/components/menu/accessibility.component.tsx
  front/src/components/menu/conditionsOfUse.component.tsx
  front/src/components/menu/infosDev.component.tsx
  front/src/components/menu/legalNotice.component.tsx
  front/src/components/menu/menu.component.tsx
  front/src/components/moodboard/moodItemsInCarousel.component.tsx
  front/src/components/moodboard/moodsCalendar.component.tsx
  front/src/components/notification/notificationToggle.component.tsx
  front/src/navigation/BottomTabNavigator.tsx
  front/src/navigation/navigation.component.tsx
  front/src/screens/moodboard/moodboard.component.tsx
  front/src/screens/notificationsCenter/notificationsCenter.component.tsx
  front/src/styles/styles.ts
  front/src/types.tsx
  front/src/utils/app/app.util.test.ts
Labels: APPLI

#1581 feat(contact): collection contact
  back/strapi/api/contacts/config/routes.json
  back/strapi/api/contacts/models/contacts.js
  back/strapi/api/contacts/models/contacts.settings.json
Labels: BO, WIDGET

#1623 fix(contact): ajout attributs
  back/strapi/api/contacts/models/contacts.settings.json
Labels: BO, WIDGET

#1627 feat: ajoutez au back office le champs rendez-vous pour la demande de…
  .github/workflows/mobile-tests.yml
  back/strapi/api/contacts/models/contacts.settings.json
  back/strapi/api/demande-de-contact/models/demande-de-contact.settings.json
Labels: BO
